---

- hosts: all
  become: yes
  gather_facts: no
  pre_tasks:
  - name: 'Updating repo'
    raw: 'apt-get update'
  - name: 'Installing Python'
    raw: 'apt-get install -y python'
  roles:
  - { role: install_iptables , tags: ["install_iptables_role"] }

- hosts: all
  become: yes
  roles:
  - { role: clean_rules, tags: ["clean_rules_role"]}

############### insert the host servers ###############

- hosts: webservers
  become: yes
  roles:
  - { role: webserver_ports, tags: ["webserver_ports_role"] }

################## end ##################

- hosts: all
  become: yes
  roles:
  - { role: rules_default, tags: ["rules_default_role"] }

- hosts: all
  become: yes
  roles:
  - { role: save_rules, tags: ["save_rules_role"] }

