---

- name: Firewall rule - allow loopback
  iptables:
    action: append
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: Firewall rule - allow established
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Firewall rule - allow ping
  iptables:
    chain: INPUT
    jump: ACCEPT
    protocol: icmp

- name: Firewall rule - allow trafego na porta 22/SSH
  iptables:
    chain: INPUT
    source: 0.0.0.0
    destination_port: "22"
    jump: ACCEPT
    protocol: tcp

- name: Firewall rule - allow 10050/ZabbixAgent
  iptables:
    chain: INPUT
    source: 0.0.0.0
    destination_port: "10050"
    jump: ACCEPT
    protocol: tcp

- name: Firewall rule - deny no ruled pass
  iptables:
    chain: INPUT
    jump: DROP
